//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Buy()
        {
            this.buy_report = new HashSet<buy_report>();
        }
    
        public int buy_id { get; set; }
        public int employee_id { get; set; }
        public int supplier_id { get; set; }
        public System.DateTime date { get; set; }
        public string state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buy_report> buy_report { get; set; }
        public virtual employee employee { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
