//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public medicine()
        {
            this.buy_report = new HashSet<buy_report>();
            this.prescription_required = new HashSet<prescription_required>();
            this.Sale_report = new HashSet<Sale_report>();
        }
    
        public int medicine_id { get; set; }
        public string name { get; set; }
        public string generic_name { get; set; }
        public Nullable<int> unit_price { get; set; }
        public Nullable<int> selling_price { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> type_id { get; set; }
        public string barcode { get; set; }
        public byte[] image { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> company_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buy_report> buy_report { get; set; }
        public virtual category category { get; set; }
        public virtual company company { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prescription_required> prescription_required { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale_report> Sale_report { get; set; }
    }
}
