//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class prescription_required
    {
        public int medicine_id { get; set; }
        public string type { get; set; }
    
        public virtual medicine medicine { get; set; }
    }
}
