//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_report
    {
        public int sale_id { get; set; }
        public int medicine_id { get; set; }
        public int count { get; set; }
        public double sale_unit_price { get; set; }
        public int sale_report_id { get; set; }
    
        public virtual medicine medicine { get; set; }
        public virtual sale sale { get; set; }
    }
}
